branch-defaults:
  deploy:
    environment: portfolio-api-production
deploy:
  artifact: build/libs/api-0.0.1-SNAPSHOT.jar
environment-defaults:
  portfolio-api-production:
    branch: null
    repository: null
global:
  application_name: portfolio-api
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
